# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects MariaDB Ansible role.
#
# The Webarchitects MariaDB Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects MariaDB Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects MariaDB Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: MariaDB configuration file section edited
  block:

    - name: Set a fact for the variables that are defined in the existing file
      ansible.builtin.set_fact:
        mariadb_cnf_file_section_existing_keys: "{{ mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_file_section_existing_keys_jpq) }}"
      vars:
        mariadb_cnf_file_section_existing_keys_jpq: "{{ mariadb_cnf_section.key }}|keys(@)"

    - name: Debug the existing and proposed MariaDB configuration file variables
      ansible.builtin.debug:
        msg:
          - "Path: {{ mariadb_cnf.path }}"
          - "Section: {{ mariadb_cnf_section.key }}"
          - "Existing: {% if mariadb_cnf_variable_pair.key in mariadb_cnf_file_section_existing_keys %}{{ mariadb_cnf_variable_pair.key }}: {{ mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_variable_jpq) }}{% endif %}"
          - "Proposed: {{ mariadb_cnf_variable_pair.key }}{% if mariadb_cnf_variable_pair.value | type_debug != 'NoneType' %}: {{ mariadb_cnf_variable_pair.value }}{% endif %}"
          - "Paoposed variable value type: {{ mariadb_cnf_variable_pair.value | type_debug  }}"
          - "Regex: ^[#][ ]{0,9}{{ mariadb_cnf_variable_pair.key | regex_replace('_', '[_-]') }}[ ]{0,9}[=]{0,1}"
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"
      when: >-
        ( mariadb_cnf_variable_pair.key not in mariadb_cnf_file_section_existing_keys ) or
        ( mariadb_cnf_variable_pair.value != mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_variable_jpq) )
      vars:
        mariadb_cnf_variable_jpq: '"{{ mariadb_cnf_section.key }}"."{{ mariadb_cnf_variable_pair.key }}"'
      loop: "{{ mariadb_cnf_section.value | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: mariadb_cnf_variable_pair
        label: "{{ mariadb_cnf_variable_pair.key }}"

    # This is to ensure that variables are written to the same place as existing commented values
    - name: Uncomment commented variables in the MariaDB configuration file that are to be edited
      ansible.builtin.lineinfile:
        path: "{{ mariadb_cnf.path }}"
        line: "{{ mariadb_cnf_variable_pair.key }}{% if mariadb_cnf_variable_pair.value | type_debug != 'NoneType' %} = {{ mariadb_cnf_variable_pair.value }}{% endif %}"
        regex: "{{ mariadb_cnf_variable_regex }}"
        state: present
        backrefs: true
        mode: "{{ mariadb_cnf.mode | default('0644') }}"
        owner: "{{ mariadb_cnf.owner | default('root') }}"
        group: "{{ mariadb_cnf.owner | default('root') }}"
      when: >-
        ( mariadb_cnf_variable_pair.key not in mariadb_cnf_file_section_existing_keys ) or
        ( mariadb_cnf_variable_pair.value != mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_variable_jpq) )
      vars:
        mariadb_cnf_variable_jpq: '"{{ mariadb_cnf_section.key }}"."{{ mariadb_cnf_variable_pair.key }}"'
        mariadb_cnf_variable_regex: "^[#][ ]{0,9}{{ mariadb_cnf_variable_pair.key | regex_replace('_', '[_-]') }}[ ]{0,9}[=]{0,1}"
      loop: "{{ mariadb_cnf_section.value | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: mariadb_cnf_variable_pair
        label: "{{ mariadb_cnf_variable_pair.key }}"

    - name: MariaDB configuration file edited for keys without values
      community.general.ini_file:
        path: "{{ mariadb_cnf.path }}"
        section: "{{ mariadb_cnf_section.key }}"
        option: "{{ mariadb_cnf_variable_pair.key }}"
        allow_no_value: true
        no_extra_spaces: false
        mode: "{{ mariadb_cnf.mode | default('0644') }}"
        owner: "{{ mariadb_cnf.owner | default('root') }}"
        group: "{{ mariadb_cnf.owner | default('root') }}"
      when: >-
        ( mariadb_cnf_variable_pair.value | type_debug == 'NoneType' ) and
        ( ( mariadb_cnf_variable_pair.key not in mariadb_cnf_file_section_existing_keys ) or
        ( mariadb_cnf_variable_pair.value != mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_variable_jpq) ) )
      vars:
        mariadb_cnf_variable_jpq: '"{{ mariadb_cnf_section.key }}"."{{ mariadb_cnf_variable_pair.key }}"'
      loop: "{{ mariadb_cnf_section.value | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: mariadb_cnf_variable_pair
        label: "{{ mariadb_cnf_variable_pair.key }} = {{ mariadb_cnf_variable_pair.value }}"

    - name: MariaDB configuration file edited for keys with values
      community.general.ini_file:
        path: "{{ mariadb_cnf.path }}"
        section: "{{ mariadb_cnf_section.key }}"
        option: "{{ mariadb_cnf_variable_pair.key }}"
        value: "{{ mariadb_cnf_variable_pair.value }}"
        no_extra_spaces: false
        mode: "{{ mariadb_cnf.mode | default('0644') }}"
        owner: "{{ mariadb_cnf.owner | default('root') }}"
        group: "{{ mariadb_cnf.owner | default('root') }}"
      when: >-
        ( mariadb_cnf_variable_pair.value | type_debug != 'NoneType' ) and
        ( ( mariadb_cnf_variable_pair.key not in mariadb_cnf_file_section_existing_keys ) or
        ( mariadb_cnf_variable_pair.value != mariadb_cnf_file_existing_vars | community.general.json_query(mariadb_cnf_variable_jpq) ) )
      vars:
        mariadb_cnf_variable_jpq: '"{{ mariadb_cnf_section.key }}"."{{ mariadb_cnf_variable_pair.key }}"'
      loop: "{{ mariadb_cnf_section.value | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: mariadb_cnf_variable_pair
        label: "{{ mariadb_cnf_variable_pair.key }} = {{ mariadb_cnf_variable_pair.value }}"

  tags:
    - mariadb
    - mariadb_conf
...
