---
- name: Use community.mysql.mysql_info to gather information about the MariaDB server version and databases
  block:

    - name: Query the MariaDB databases, users and version using a socket
      community.mysql.mysql_info:
        filter:
          - databases
          - users
          - version
        return_empty_dbs: true
        login_user: root
        login_unix_socket: "{{ mariadb_socket }}"
      register: mariadb_info

    - name: Debug MariaDB info
      ansible.builtin.debug:
        var: mariadb_info
        verbosity: 3

    - name: Set a variable for the MariaDB version
      ansible.builtin.set_fact:
        mariadb_version: "{{ mariadb_info.version.major }}.{{ mariadb_info.version.minor }}.{{ mariadb_info.version.release }}"

    - name: Debug MariaDB version
      ansible.builtin.debug:
        var: mariadb_version
        verbosity: 2

    - name: Set a variable for the MariaDB databases
      ansible.builtin.set_fact:
        mariadb_databases: "{{ mariadb_databases | default([]) }} + [ '{{ db.key }}' ]"
      loop: "{{ mariadb_info.databases | dict2items }}"
      loop_control:
        loop_var: db
        label: "{{ db.key }}"

    - name: Debug MariaDB databases
      ansible.builtin.debug:
        var: mariadb_databases
        verbosity: 2

  tags:
    - mariadb
...
