---
- name: Use command to gather information about the MariaDB server version and databases
  block:

    - name: Run mariadb -V to get the version string
      ansible.builtin.command: mariadb -V
      check_mode: false
      changed_when: false
      register: mariadb_v

    - name: Set a variable for the Mariadb version
      ansible.builtin.set_fact:
        mariadb_version: "{{ mariadb_v.stdout.split(' ')[5] | regex_replace('-MariaDB,') }}"

    - name: Debug MariaDB version
      ansible.builtin.debug:
        var: mariadb_version
        verbosity: 2

    - name: Query the databases
      ansible.builtin.command: mysql -BNe "show databases"
      check_mode: false
      changed_when: false
      register: mariadb_show_databases

    - name: Set a variable for the MariaDB databases
      ansible.builtin.set_fact:
        mariadb_databases: "{{ mariadb_show_databases.stdout_lines }}"

    - name: Debug MariaDB databases
      ansible.builtin.debug:
        var: mariadb_databases
        verbosity: 2

  tags:
    - mariadb
...
