---
- name: Use community.mysql.mysql_info to gather information about the MariaDB server version and databases
  block:

    - name: Query the MariaDB databases, users and version using a socket
      community.mysql.mysql_info:
        filter:
          - databases
          - users
          - version
        return_empty_dbs: true
        login_user: root
        login_unix_socket: "{{ mariadb_socket }}"
      register: mariadb_info

    - name: Debug MariaDB info
      ansible.builtin.debug:
        var: mariadb_info
        verbosity: 3

    - name: Set a variable for the MariaDB version
      ansible.builtin.set_fact:
        mariadb_version: "{{ mariadb_info.version.major }}.{{ mariadb_info.version.minor }}.{{ mariadb_info.version.release }}"

    - name: Debug MariaDB version
      ansible.builtin.debug:
        var: mariadb_version
        verbosity: 2

    - name: Generate a list of databases omitting lost+found if present
      ansible.builtin.set_fact:
        mariadb_databases: "{{ mariadb_info.databases.keys() | list | reject('search', 'lost+found') | list }}"

    - name: Debug MariaDB databases
      ansible.builtin.debug:
        var: mariadb_databases
        verbosity: 2

  tags:
    - mariadb
...
