---
- name: Tasks when Ansible MariaDB root plugin local facts failed
  block:

    - name: Stat the socket path
      ansible.builtin.stat:
        path: "{{ mariadb_socket }}"
      register: mariadb_socket_path
      when: mariadb_socket is defined

    - name: Warn that the MariaDB socket doesn't exist
      ansible.builtin.debug:
        msg: "The MariaDB socket at {{ mariadb_socket }} could not be found, please check the value of the mariadb_socket Ansible variable and the value of the MariaDB socket variable"
      when:
        - mariadb_socket is defined
        - not mariadb_socket_path.stat.exists | bool

    - name: Stat /root/.my.cnf
      ansible.builtin.stat:
        path: /root/.my.cnf
      register: mariadb_root_mycnf

    - name: Fail since /root/.my.cnf doesn't exist
      ansible.builtin.assert:
        that:
          - mariadb_root_mycnf.stat.exists
        fail_message:
          - "This role has been unable to login as the root user using a socket or credentials from /root/.my.cnf"
          - "Please ensure that /root/.my.cnf contains the root login details when using mysql_native_password for authentication"

    - name: Load the passwd from /root/.my.cnf
      ansible.builtin.command: "my_print_defaults --defaults-file='/root/.my.cnf' client"
      register: mariadb_my_print_defaults_command
      no_log: true

    - name: Set a fact for the mariadb_root_password
      ansible.builtin.set_fact:
        mariadb_root_password: "{{ line | regex_replace('--password=') | trim }}"
      when: line is regex('--password=')
      loop: "{{ mariadb_my_print_defaults_command.stdout_lines }}"
      loop_control:
        loop_var: line
      no_log: true

    - name: Fail since a password could not be read from /root/.my.cnf
      ansible.builtin.assert:
        that:
          - ( mariadb_root_password is defined ) and ( mariadb_root_password | length > 0 )
        fail_msg:
          - "A password could not be read from /root/.my.cnf"
          - "Please ensure that /root/.my.cnf contains the root login details when using mysql_native_password for authentication"

    - name: Test the MariaDB root password
      ansible.builtin.command: mariadb -u "root" -p "{{ mariadb_root_password }}" -h "localhost" -p "3306" -BNe "status" mysql
      register: mariadb_command_status
      failed_when: mariadb_command_status.rc not regex(0|1)

    - name: Fail since the root password in /root/.my.cnf didn't work
      ansible.builtin.assert:
        that:
          - mariadb_command_status.rc == 0
        fail_msg:
          - "The root password that has been read from /root/.my.cnf doesn't appear to work"
          - "Please ensure that /root/.my.cnf contains the root login details when using mysql_native_password for authentication"

  when: ansible_facts.ansible_local.mariadb_root.state == "absent"
  tags:
    - mariadb
...
