---
# https://stackoverflow.com/a/40059130
- name: debconf and debconf-utils packages present 
  apt:
    pkg:
      - debconf
      - debconf-utils
    state: latest
    update_cache: yes
  tags:
    - mariadb

- name: Stat /root/.my.cnf
  stat:
    path: /root/.my.cnf
  register: root_mycnf_stat
  tags:
    - mariadb

# when mariadb_root_password equals "set", load the password from 
# /root/.my.cnf if it exists and if not generate one  
- block:

  - name: Load the passwd from /root/.my.cnf
    shell: "my_print_defaults --defaults-file='/root/.my.cnf' client | grep '^--password' | sed -e 's/--password=//'"
    register: mariadb_root_password_read
    when: root_mycnf_stat.stat.exists == True
    tags:
      - mariadb

  - name: Set a fact for the mariadb_root_password
    set_fact:
      mariadb_root_password: "{{ mariadb_root_password_read.stdout | trim | quote }}"
    when: root_mycnf_stat.stat.exists == True
    tags:
      - mariadb

  - name: Generate a random password for MariaDB root
    command: pwgen -n 16 1
    register: mariadb_root_password_gen
    when: root_mycnf_stat.stat.exists == False
    tags:
      - mariadb

  - name: Set a fact for the mariadb_root_password
    set_fact:
      mariadb_root_password: "{{ mariadb_root_password_gen.stdout | trim | quote }}"
    when: root_mycnf_stat.stat.exists == False
    tags:
      - mariadb

  - debug:
      msg: "mariadb_root_password: {{ mariadb_root_password }}"
      verbosity: 1
    tags:
      - mariadb

  when: mariadb_root_password == "set" 

- debug:
    msg: "mariadb_root_password: {{ mariadb_root_password }}"
    verbosity: 1
  tags:
    - mariadb

- name: Specify MySQL root password before installing
  # without this, auth_socket will be used for root@localhost, and we won't be able to set the password
  # https://stackoverflow.com/a/40059130
  debconf: 
    name: mariadb-server
    question: "mariadb-server/root_password"
    value: "{{ mariadb_root_password | quote }}"
    vtype: "password"
  become: true
  tags:
    - mariadb

- name: Confirm MySQL root password before installing
  debconf: 
    name: mariadb-server
    question: "mariadb-server/root_password_again"
    value: "{{ mariadb_root_password | quote }}"
    vtype: "password"
  become: true
  tags:
    - mariadb

- name: mariadb-server, mariadb-client and other packages present
  apt:
    pkg: 
      - mariadb-server
      - mariadb-client
      - mysqltuner
      - python-mysqldb
    state: latest
    update_cache: no
  tags:
    - mariadb

- name: "mariadb_root_password written to {{ mariadb_mycnf }}"
  template:
    src: templates/root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400
    force: yes
  register: mariadb_root_password_written
  tags:
    - mariadb

- name: MariaDB root user password set 
  mysql_user:
    #login_user: root
    #login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    password: "{{ mariadb_root_password | quote }}"
    state: present
    sql_log_bin: yes
    priv: "*.*:ALL,GRANT"
    update_password: always
  register: mariadb_root_password_set
  tags:
    - mariadb
