---
- name: Set the  MariaDB root password
  block:

    - name: Generate a root password when /root/.my.cnf doesn't exist
      block:

        - name: Generate a random password for MariaDB root
          ansible.builtin.command: "pwgen -n {{ 24 | random(14) }} 1"
          register: mariadb_root_password_gen
          no_log: true

        - name: Set a fact for the mariadb_root_password
          ansible.builtin.set_fact:
            mariadb_root_password: "{{ mariadb_root_password_gen.stdout | trim }}"
          no_log: true

      when: not root_mycnf_stat.stat.exists

    # https://www.percona.com/blog/2016/03/16/change-user-password-in-mysql-5-7-with-plugin-auth_socket/

    - name: Enable MariaDB root logins with a password
      community.mysql.mysql_query:
        query:
          - "UPDATE user SET authentication_string=PASSWORD('{{ mariadb_root_password }}'), plugin='mysql_native_password' WHERE User='root' AND Host='localhost'"
          - FLUSH PRIVILEGES
        login_db: mysql
        login_user: root
      no_log: true
      when: mariadb_community

    - name: Enable MariaDB root logins with a password
      ansible.builtin.command: mysql -uroot -e "UPDATE mysql.user SET authentication_string=PASSWORD('{{ mariadb_root_password }}'), plugin='mysql_native_password' WHERE User='root' AND Host='localhost'; FLUSH PRIVILEGES;"
      no_log: true
      when: not mariadb_community

    - name: MariaDB root password written to /root/.my.cnf
      ansible.builtin.template:
        src: templates/root.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0400
        force: true
      no_log: true

  tags:
    - mariadb
...
