---
- debug:
    msg: "mariadb_username: {{ mariadb_username }}"
    verbosity: 1
  when: mariadb_username is defined and mariadb_username != ""
  tags:
    - mariadb

- debug:
    msg: "mariadb_database: {{ mariadb_database }}"
    verbosity: 1
  when: mariadb_database is defined and mariadb_database != ""
  tags:
    - mariadb

- debug:
    msg: "mariadb_password: {{ mariadb_password }}"
    verbosity: 1
  when: mariadb_password is defined and mariadb_password != ""
  tags:
    - mariadb

- name: Check if a user account matching the MariaDB username exists
  shell: "grep '^{{ mariadb_username }}:' /etc/passwd | awk -F : '{ print$6 }'" 
  register: mariadb_username_home_check
  tags:
    - mariadb

- debug:
    msg: "mariadb_username_home_check.stdout: {{ mariadb_username_home_check.stdout }}"
    verbosity: 1
  tags:
    - mariadb

- debug:
    msg: "mariadb_username_home_check.stderr: {{ mariadb_username_home_check.stderr }}"
    verbosity: 1
  tags:
    - mariadb
  
- name: Set the path and filename for the .my.cnf file
  set_fact:
    mariadb_mycnf: "/root/.{{ mariadb_username }}.my.cnf" 
  when: mariadb_username_home_check is not defined or mariadb_username_home_check.stdout == ""
  tags:
    - mariadb

- name: Set the path and filename for the .my.cnf file
  set_fact:
    mariadb_mycnf: "{{ mariadb_username_home_check.stdout }}/.my.cnf" 
  when: mariadb_username_home_check is defined and mariadb_username_home_check.stdout != ""
  tags:
    - mariadb

- debug:
    msg: "mariadb_mycnf: {{ mariadb_mycnf }}"
    verbosity: 1
  when: mariadb_mycnf is defined and mariadb_mycnf != ""
  tags:
    - mariadb

- block:

  - name: Generate a random password for mariadb_username if none is set
    command: pwgen -n 16 1
    register: mariadb_password_gen
    tags:
      - mariadb
  
  - name: Set a fact for the mariadb_password
    set_fact:
      mariadb_password: "{{ mariadb_password_gen.stdout | trim | quote }}"
    tags:
      - mariadb

  when: mariadb_password is not defined and mariadb_password == ""

- name: Set the mariadb_database name to match the mariadb_username
  set_fact:
    mariadb_database: "{{ mariadb_username }}"
  when: mariadb_database is not defined and mariadb_database == ""
  tags:
    - mariadb

- name: MariaDB database present
  mysql_db:
    name: "{{ mariadb_database }}"
    state: present
  tags:
    - mariadb
  
- name: MariaDB user present
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mariadb_username }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    state: present
    update_password: on_create
  tags:
    - mariadb

