---
- name: Debug mariadb_root_password
  debug:
    var: mariadb_root_password
    verbosity: 1
  tags:
    - mariadb

- name: Stat /root/.my.cnf
  stat:
    path: /root/.my.cnf
  register: root_mycnf_stat
  tags:
    - mariadb

- name: Read the MariaDB root password from /root/.my.cnf
  block:

    - name: Load the passwd from /root/.my.cnf
      command: "my_print_defaults --defaults-file='/root/.my.cnf' client"
      register: mariadb_my_print_defaults_command
      # no_log: true

    - name: Set a fact for the mariadb_root_password
      set_fact:
        mariadb_root_password: "{{ line | regex_replace('^--password=') | trim }}"
      when: line is regex('^--password=')
      loop: "{{ mariadb_my_print_defaults_command.stdout_lines }}"
      loop_control:
        loop_var: line
      # no_log: true

  when: root_mycnf_stat.stat.exists == True
  tags:
    - mariadb

- name: Set the MariaDB root password
  include_tasks: mariadb_root_password.yml
  when: ( mariadb_root_password is defined ) and ( mariadb_root_password == "set" )
  tags:
    - mariadb

- name: Set the MariaDB root use to use socket authentication
  include_tasks: mariadb_root_socket.yml
  when: ( mariadb_root_password is defined ) and ( mariadb_root_password == "socket" )
  tags:
    - mariadb
...
