# https://www.percona.com/blog/2016/03/16/change-user-password-in-mysql-5-7-with-plugin-auth_socket/
---
- name: Set the  MariaDB root password
  block:

    - name: Generate a root password when /root/.my.cnf doesn't exist
      block:

        - name: Generate a random password for MariaDB root
          ansible.builtin.command: "pwgen -n {{ 24 | random(14) }} 1"
          register: mariadb_root_password_gen
          no_log: true

        - name: Set a fact for the mariadb_root_password
          ansible.builtin.set_fact:
            mariadb_root_password: "{{ mariadb_root_password_gen.stdout | trim }}"
          no_log: true

      when: not root_mycnf_stat.stat.exists

    - name: Enable MariaDB root logins with a password
      community.mysql.mysql_query:
        query:
          - "UPDATE user SET authentication_string=PASSWORD('{{ mariadb_root_password }}'), plugin='mysql_native_password' WHERE User='root' AND Host='localhost'"
          - FLUSH PRIVILEGES
        login_db: mysql
        login_user: root
        login_unix_socket: /run/mysqld/mysqld.sock
      when: mariadb_community
      no_log: true

    # - name: Enable MariaDB root logins with a password
    #   ansible.builtin.command: mysql -uroot -e "UPDATE mysql.user SET authentication_string=PASSWORD('{{ mariadb_root_password }}'), plugin='mysql_native_password' WHERE User='root' AND Host='localhost'; FLUSH PRIVILEGES;"
    #   when: not mariadb_community
    #   no_log: true

    - name: MariaDB root password written to /root/.my.cnf
      ansible.builtin.template:
        src: templates/root.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0400
        force: true
      no_log: true

    - name: Query the MariaDB databases, users and version using the /root/.my.cnf file
      community.mysql.mysql_info:
        filter:
          - users
        return_empty_dbs: true
        login_user: root
        config_file: /root/.my.cnf
      register: mariadb_info

    - name: Set a variable for the root authentication plugin
      ansible.builtin.set_fact:
        mariadb_root_auth_current: "{{ mariadb_info.users.localhost.root.plugin }}"

    - name: Debug MariaDB root authentication plugin
      ansible.builtin.debug:
        var: mariadb_root_auth_current
        verbosity: 2

  tags:
    - mariadb
...
