# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects MariaDB Ansible role.
#
# The Webarchitects MariaDB Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects MariaDB Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects MariaDB Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install and run mysqltuner for MariaDB
  block:

    - name: Check the latest version of MySQLTuner
      ansible.builtin.uri:
        url: https://github.com/major/MySQLTuner-perl/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: mariadb_mysqltuner_headers

    - name: Debug MySQLTuner latest headers
      ansible.builtin.debug:
        msg:
          - "Location: {{ mariadb_mysqltuner_headers.location }}"
          - "Path: {{ mariadb_mysqltuner_headers.location | ansible.builtin.urlsplit('path') }}"
          - "Version: {{ mariadb_mysqltuner_headers.location | ansible.builtin.urlsplit('path') | ansible.builtin.basename | ansible.builtin.regex_replace('^v') }}"
        verbosity: 2
      tags:
        - debug

    - name: Set a fact for the latest version of MySQLTuner
      ansible.builtin.set_fact:
        mariadb_mysqltuner_version_latest: "{{ mariadb_mysqltuner_headers.location | ansible.builtin.urlsplit('path') | ansible.builtin.basename | ansible.builtin.regex_replace('^v') }}"

    - name: Debug mariadb_mysqltuner_version_latest
      ansible.builtin.debug:
        var: mariadb_mysqltuner_version_latest
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Stat /usr/local/bin/mysqltuner
      ansible.builtin.stat:
        path: /usr/local/bin/mysqltuner
      register: mariadb_mysqltuner_local_bin

    - name: Check /usr/local/bin/mysqltuner version
      block:

        - name: Run /usr/local/bin/mysqltuner --help
          ansible.builtin.command: /usr/local/bin/mysqltuner --help
          check_mode: false
          changed_when: false
          register: mariadb_mysqltuner_local_help

        - name: Debug mariadb_mysqltuner_local_help
          ansible.builtin.debug:
            var: mariadb_mysqltuner_local_help
            verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"
          tags:
            - debug

        - name: Set a fact for the /usr/local/bin/mysqltuner version
          ansible.builtin.set_fact:
            mariadb_mysqltuner_version_local: "{{ (mariadb_mysqltuner_local_help.stdout_lines[1] | trim | ansible.builtin.split(' '))[1] }}"

        - name: Debug mariadb_mysqltuner_version_local
          ansible.builtin.debug:
            var: mariadb_mysqltuner_version_local
            verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
          tags:
            - debug

        - name: Check that mariadb_mysqltuner_version_local is a version number
          ansible.builtin.assert:
            that:
              - mariadb_mysqltuner_version_local is ansible.builtin.version('1.0.0', 'gt', version_type='semver')
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

      when: mariadb_mysqltuner_local_bin.stat.exists | bool

    - name: Set a fact for the version of MySQLTuner that is required and the Debian / Ubuntu version
      ansible.builtin.set_fact:
        mariadb_mysqltuner_version_required: "{% if mariadb_mysqltuner_version == 'latest' %}{{ mariadb_mysqltuner_version_latest }}{% elif mariadb_mysqltuner_version == 'master' %}master{% else %}{{ mariadb_mysqltuner_version }}{% endif %}"
        mariadb_mysqltuner_version_debian: "{{ mariadb_mysqltuner_versions | community.general.json_query(mariadb_jpq.tunerver) }}"

    - name: Debug the MySQLTuner version required
      ansible.builtin.debug:
        var: mariadb_mysqltuner_version_required
      tags:
        - debug

    - name: Debug the Debian / Ubuntu version of MySQLTuner
      ansible.builtin.debug:
        var: mariadb_mysqltuner_version_debian
      tags:
        - debug

    - name: Fail if the Debian / Ubuntu version of MySQLTuner is not a version number
      ansible.builtin.assert:
        that:
          - mariadb_mysqltuner_version_debian is ansible.builtin.version('1.0.0', 'gt', version_type='semver')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
        fail_msg: "Please check that {{ ansible_facts.distribution_release }} is in the mariadb_mysqltuner_versions array."

    - name: Use a Debian version of MySQLTuner
      block:

        - name: Source MySQLTuner script absent
          ansible.builtin.file:
            path: /usr/local/bin/mysqltuner
            state: absent

        - name: Source MySQLTuner code absent
          ansible.builtin.file:
            path: /usr/local/src/MySQLTuner-perl
            state: absent

        - name: Source MySQLTuner basic_passwords.txt file absent
          ansible.builtin.file:
            path: /usr/local/bin/basic_passwords.txt
            state: absent

        - name: Source MySQLTuner vulnerabilities.csv absent
          ansible.builtin.file:
            path: /usr/share/mysqltuner/vulnerabilities.csv
            state: absent
          when: ( "mysqltuner" not in ansible_facts.ansible_local.dpkg.installed )

        - name: Debian MySQLTuner present
          ansible.builtin.apt:
            pkg:
              - mysqltuner
            state: present
          register: mariadb_mysqltuner_present
          when: >-
            ( ansible_facts.ansible_local.dpkg.installed is not defined ) or
            ( "mysqltuner" not in ansible_facts.ansible_local.dpkg.installed )

        - name: Re-read Ansible local facts
          ansible.builtin.setup:
            filter: ansible_local

      when:
        - mariadb_mysqltuner_version_required != "master"
        - mariadb_mysqltuner_version_required is ansible.builtin.version(mariadb_mysqltuner_version_debian, 'eq')

    - name: Install MySQLTuner from GitHub
      block:

        - name: Debian MySQLTuner absent
          ansible.builtin.apt:
            pkg:
              - mysqltuner
            state: absent
          register: mariadb_mysqltuner_absent
          when: >-
            ( ansible_facts.ansible_local.dpkg.installed is not defined ) or
            ( "mysqltuner" in ansible_facts.ansible_local.dpkg.installed )

        - name: Debian git package present
          ansible.builtin.apt:
            pkg:
              - git
              - libjson-perl
            state: present
          register: mariadb_git_present
          when: >-
            ( ansible_facts.ansible_local.dpkg.installed is not defined ) or
            ( "git" not in ansible_facts.ansible_local.dpkg.installed ) or
            ( "libjson-perl" not in ansible_facts.ansible_local.dpkg.installed )

        - name: Re-read Ansible local facts  # noqa: no-handler
          ansible.builtin.setup:
            filter: ansible_local
          when: >-
            ( ( mariadb_mysqltuner_absent.changed is defined ) and
            ( mariadb_mysqltuner_absent.changed | bool ) ) or
            ( ( mariadb_git_present.changed is defined ) and
            ( mariadb_git_present.changed | bool ) )

        - name: Source MySQLTuner install using git
          block:

            - name: MySQLTuner source code present
              ansible.builtin.git:
                repo: https://github.com/major/MySQLTuner-perl.git
                dest: /usr/local/src/MySQLTuner-perl
                version: "{% if mariadb_mysqltuner_version_required == 'master' %}master{% else %}v{{ mariadb_mysqltuner_version_required }}{% endif %}"
                depth: 1
                update: true

            - name: Check that MySQLTuner code is present
              ansible.builtin.stat:
                path: /usr/local/src/MySQLTuner-perl/mysqltuner.pl
              register: mariadb_mysqltuner_script

            - name: MySQLTuner script in place
              ansible.builtin.copy:
                src: /usr/local/src/MySQLTuner-perl/mysqltuner.pl
                dest: /usr/local/bin/mysqltuner
                remote_src: true
                mode: "0755"
                owner: root
                group: root
              when: mariadb_mysqltuner_script.stat.exists | bool

            - name: Directory for MySQLTuner assets in place
              ansible.builtin.file:
                path: /usr/share/mysqltuner
                state: directory
                mode: "0755"
                owner: root
                group: root

            - name: Check that MySQLTuner passwords is present
              ansible.builtin.stat:
                path: /usr/local/src/MySQLTuner-perl/basic_passwords.txt
              register: mariadb_mysqltuner_passwords

            - name: MySQLTuner basic_passwords.txt file in place
              ansible.builtin.copy:
                src: /usr/local/src/MySQLTuner-perl/basic_passwords.txt
                dest: /usr/local/bin/basic_passwords.txt
                remote_src: true
                mode: "0644"
                owner: root
                group: root
              when: mariadb_mysqltuner_passwords.stat.exists | bool

            - name: Check that MySQLTuner vulnerabilities is present
              ansible.builtin.stat:
                path: /usr/local/src/MySQLTuner-perl/vulnerabilities.csv
              register: mariadb_mysqltuner_vulnerabilities

            - name: MySQLTuner vulnerabilities.csv file in place
              ansible.builtin.copy:
                src: /usr/local/src/MySQLTuner-perl/vulnerabilities.csv
                dest: /usr/share/mysqltuner/vulnerabilities.csv
                remote_src: true
                mode: "0644"
                owner: root
                group: root
              when: mariadb_mysqltuner_vulnerabilities.stat.exists | bool

          when: >-
            ( ansible_facts.ansible_local.dpkg.installed is not defined ) or
            ( "git" in ansible_facts.ansible_local.dpkg.installed )

      when: >-
        (mariadb_mysqltuner_version_required == 'master') or
        (mariadb_mysqltuner_version_required is ansible.builtin.version(mariadb_mysqltuner_version_debian, 'ne'))

    - name: Check that mysqltuner is installed
      ansible.builtin.command: which mysqltuner
      check_mode: false
      changed_when: false
      register: mariadb_mysqltuner_which
      failed_when: mariadb_mysqltuner_which.rc is not regex('^0|1$')

    - name: Check that /usr/share/mysqltuner/vulnerabilities.csv is present
      ansible.builtin.stat:
        path: /usr/share/mysqltuner/vulnerabilities.csv
      register: mariadb_mysqltuner_vulnerabilities_csv

    - name: Gather service facts
      ansible.builtin.service_facts:
      register: mariadb_service_facts

    - name: Run mysqltuner when it is installed and MariaDB is running
      block:

        # Full full results run `mysqltuner --json --cvefile=/usr/share/mysqltuner/vulnerabilities.csv | jq`
        - name: Run mysqltuner
          ansible.builtin.command: >-
            mysqltuner --json
            {% if mariadb_mysqltuner_vulnerabilities_csv.stat.exists | bool %}--cvefile=/usr/share/mysqltuner/vulnerabilities.csv{% endif %}
          check_mode: false
          changed_when: false
          register: mariadb_mysqltuner_command
          failed_when: >-
            ( "JSON Module is needed" in mariadb_mysqltuner_command.stdout ) or
            ( mariadb_mysqltuner_command.rc != 0 )
          tags:
            - molecule-idempotence-notest

        - name: Set fact for mysqltuner results
          block:

            - name: Set facts for mysqltuner results
              ansible.builtin.set_fact:
                mariadb_mysqltuner_results: "{{ mariadb_mysqltuner_command.stdout | ansible.builtin.from_json }}"
                mariadb_mysqltuner_adjust_variables: "{{ mariadb_mysqltuner_command.stdout | ansible.builtin.from_json | community.general.json_query(mariadb_jpq.adjvars) }}"
                mariadb_mysqltuner_recommendations: "{{ mariadb_mysqltuner_command.stdout | ansible.builtin.from_json | community.general.json_query(mariadb_jpq.recs) }}"
                mariadb_mysqltuner_fragmented_tables: "{{ mariadb_mysqltuner_command.stdout | ansible.builtin.from_json | community.general.json_query(mariadb_jpq.fragtabs) }}"
                mariadb_mysqltuner_cve: "{{ mariadb_mysqltuner_command.stdout | ansible.builtin.from_json | community.general.json_query(mariadb_jpq.cve) }}"

            - name: Print mysqltuner full results when running with -v
              ansible.builtin.debug:
                var: mariadb_mysqltuner_results
              when:
                - mariadb_mysqltuner_results | length > 0
                - ansible_verbosity >= 1
              tags:
                - debug

            - name: Print mysqltuner results for Adjust variables
              ansible.builtin.debug:
                var: mariadb_mysqltuner_adjust_variables
              when:
                - mariadb_mysqltuner_adjust_variables != []
                - mariadb_mysqltuner_adjust_variables | length > 0
              tags:
                - debug

            - name: Print mysqltuner results for Fragmented tables
              ansible.builtin.debug:
                var: mariadb_mysqltuner_fragmented_tables
              when:
                - mariadb_mysqltuner_fragmented_tables != []
                - mariadb_mysqltuner_fragmented_tables | length > 0
              tags:
                - debug

            - name: Print mysqltuner results for Recommendations
              ansible.builtin.debug:
                var: mariadb_mysqltuner_recommendations
              when:
                - mariadb_mysqltuner_recommendations != []
                - mariadb_mysqltuner_recommendations | length > 0
              tags:
                - debug

            - name: Print mysqltuner results for CVE
              ansible.builtin.debug:
                var: mariadb_mysqltuner_cve
              when:
                - mariadb_mysqltuner_cve != []
                - mariadb_mysqltuner_cve | length > 0
              tags:
                - debug

          rescue:

            - name: Check mysqltuner path
              ansible.builtin.command: which mysqltuner
              check_mode: false
              changed_when: false
              register: mariadb_mysqltuner_which

            - name: Set a fact for the mysqltuner path
              ansible.builtin.set_fact:
                mariadb_mysqltuner_path: "{{ mariadb_mysqltuner_which.stdout }}"

            - name: Debug mariadb_mysqltuner_path
              ansible.builtin.debug:
                var: mariadb_mysqltuner_path

            - name: "Slurp {{ mariadb_mysqltuner_path }}"
              ansible.builtin.slurp:
                src: "{{ mariadb_mysqltuner_path }}"
              register: mariadb_mysqltuner_file_b64encoded

            - name: Decode the base64 encoded version of mysqltuner, split it by lines and set a fact for the version
              ansible.builtin.set_fact:
                mariadb_mysqltuner_file_line2: "{{ (mariadb_mysqltuner_file_b64encoded['content'] | ansible.builtin.b64decode | trim ).split('\n')[1] }}"

            - name: Debug mariadb_mysqltuner_file_line2
              ansible.builtin.debug:
                var: mariadb_mysqltuner_file_line2

            - name: Fail because mysqltuner failed
              ansible.builtin.fail:
                msg:
                  - "Path {{ mariadb_mysqltuner_path }}"
                  - "Line 2 {{ mariadb_mysqltuner_file_line2 }}"
                  - "Return code {{ mariadb_mysqltuner_command.rc }}"
                  - "Standard out {{ mariadb_mysqltuner_command.stdout }}"
                  - "Standard error {{ mariadb_mysqltuner_command.stderr }}"

          when: mariadb_mysqltuner_command is defined

      when:
        - mariadb_mysqltuner_which.rc == 0
        - (mariadb_service_facts | community.general.json_query(mariadb_jpq.service)).status == "running"

  tags:
    - mariadb
    - mariadb_conf
    - mariadb_mysqltuner
    - mysqltuner
...
