---
- name: Install the MariaDB sys schema
  block:

    - name: MariaDB sys repo directory present
      ansible.builtin.file:
        path: /usr/local/src/mariadb-sys
        state: directory
        mode: 0750

    - name: MariaDB sys schema repo present
      ansible.builtin.git:
        repo: https://github.com/webarch-coop/mariadb-sys.git
        dest: /usr/local/src/mariadb-sys
        clone: true
        version: master

    # Bash might be /bin/bash or /usr/bin/bash
    - name: Run which bash
      ansible.builtin.command: which bash
      check_mode: false
      changed_when: false
      register: which_bash
      failed_when: which_bash.stdout is not regex('\/bash$')

    - name: Set a variable for the path to Bash
      ansible.builtin.set_fact:
        bash: "{{ which_bash.stdout }}"

    # TODO Update the following task to use community.mysql.mysql_db when it is in Debian Ansible
    - name: Import the sys schema
      ansible.builtin.shell: |
        set -e -o pipefail
        mysql < ./mariadb_sys_install.sql
      args:
        executable: "{{ bash }}"
        chdir: /usr/local/src/mariadb-sys
      when: not mariadb_community

    - name: Import the sys schema
      community.mysql.mysql_db:

  tags:
    - mariadb
...
