---
- name: Install the MariaDB sys schema
  block:

    - name: MariaDB sys repo directory present
      ansible.builtin.file:
        path: /usr/local/src/mariadb-sys
        state: directory
        mode: 0755

    - name: MariaDB sys schema repo present
      ansible.builtin.git:
        repo: https://github.com/webarch-coop/mariadb-sys.git
        dest: /usr/local/src/mariadb-sys
        clone: true
        version: master

    - name: Use shell to import the MariaDB sys schema
      block:

        # Bash might be /bin/bash or /usr/bin/bash
        - name: Run which bash
          ansible.builtin.command: which bash
          check_mode: false
          changed_when: false
          register: which_bash
          failed_when: which_bash.stdout is not regex('\/bash$')

        - name: Set a variable for the path to Bash
          ansible.builtin.set_fact:
            bash: "{{ which_bash.stdout }}"

        - name: Import the sys schema using the shell module
          ansible.builtin.shell: |
            set -e -o pipefail
            mysql < ./mariadb_sys_install.sql
          changed_when: true
          args:
            executable: "{{ bash }}"
            chdir: /usr/local/src/mariadb-sys

      when: mariadb_root_auth_current == "password"

    - name: Use import the sys schema using community.mysql.mysql_db and a socket
      community.mysql.mysql_db:
        name: all
        state: import
        target: /usr/local/src/mariadb-sys/mariadb_sys_install.sql
        login_user: root
        login_unix_socket: /run/mysqld/mysqld.sock
      when: mariadb_root_auth_current is regex('socket$')

  tags:
    - mariadb
...
