---
- name: Get the latest date from the tzdata package changelog
  command: dpkg-parsechangelog -l /usr/share/doc/tzdata/changelog.Debian.gz -S Date
  check_mode: false
  changed_when: false
  register: mariadb_tzdata_deb_date
  tags:
    - mariadb

- name: Set a fact for the date of the latest version
  set_fact:
    mariadb_tzdata_latest: "{{ mariadb_tzdata_deb_date.stdout }}"
  tags:
    - mariadb

- name: Check if the /root/.my.tzdata file exists
  stat:
    path: /root/.my.tzdata
  register: mariadb_tzdata_mariadb_file
  tags:
    - mariadb

- name: Tasks for when the /root/.my.tzdata file exists
  block:

    - name: Slurp the contents from the /root/.my.tzdata file
      slurp:
        src: /root/.my.tzdata
      register: mariadb_tzdata_mariadb_file_b64encoded

    - name: Set a fact for the date in the /root/.my.tzdata file
      set_fact:
        mariadb_tzdata_mariadb: "{{ mariadb_tzdata_mariadb_file_b64encoded['content'] | b64decode | trim }}"

    - name: Debug the value of mariadb_tzdata_mariadb and mariadb_tzdata_deb_date
      debug:
        msg:
          - "mariadb_tzdata_latest: {{ mariadb_tzdata_latest }}"
          - "mariadb_tzdata_mariadb: {{ mariadb_tzdata_mariadb }}"
        verbosity: 1

  when: mariadb_tzdata_mariadb_file.stat.exists
  tags:
    - mariadb

- name: Import the tzdata into the mysql database tables
  block:

    - name: Import the time zone data from /usr/share/zoneinfo
      shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql

    - name: Update the /root/.my.tzdata file
      shell: dpkg-parsechangelog -l /usr/share/doc/tzdata/changelog.Debian.gz -S Date > /root/.my.tzdata

  when: ( not mariadb_tzdata_mariadb_file.stat.exists ) or ( mariadb_tzdata_mariadb_file.stat.exists and mariadb_tzdata_mariadb != mariadb_tzdata_latest )
  tags:
    - mariadb
...
