# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects MariaDB Ansible role.
#
# The Webarchitects MariaDB Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects MariaDB Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects MariaDB Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: MariaDB TZ tasks
  block:

    - name: Package dpkg-dev present
      ansible.builtin.apt:
        pkg:
          - dpkg-dev
        state: present

    - name: Check that the Debian tzdata changelog is present
      ansible.builtin.stat:
        path: /usr/share/doc/tzdata/changelog.Debian.gz
      register: mariadb_tzdata_changelog

    - name: Update the timezone data
      block:

        - name: Get the latest date from the tzdata package changelog
          ansible.builtin.command: dpkg-parsechangelog -l /usr/share/doc/tzdata/changelog.Debian.gz -S Date
          check_mode: false
          changed_when: false
          register: mariadb_tzdata_deb_date

        - name: Set a fact for the date of the latest version
          ansible.builtin.set_fact:
            mariadb_tzdata_latest: "{{ mariadb_tzdata_deb_date.stdout }}"

        - name: Check if the /root/.my.tzdata file exists
          ansible.builtin.stat:
            path: /root/.my.tzdata
          register: mariadb_tzdata_mariadb_file

        - name: Tasks for when the /root/.my.tzdata file exists
          block:

            - name: Slurp the contents from the /root/.my.tzdata file
              ansible.builtin.slurp:
                src: /root/.my.tzdata
              register: mariadb_tzdata_mariadb_file_b64encoded

            - name: Set a fact for the date in the /root/.my.tzdata file
              ansible.builtin.set_fact:
                mariadb_tzdata_mariadb: "{{ mariadb_tzdata_mariadb_file_b64encoded['content'] | b64decode | trim }}"

            - name: Debug the values of mariadb_tzdata_latest and mariadb_tzdata_mariadb
              ansible.builtin.debug:
                msg:
                  - "mariadb_tzdata_latest: {{ mariadb_tzdata_latest }}"
                  - "mariadb_tzdata_mariadb: {{ mariadb_tzdata_mariadb }}"
                verbosity: 1

          when: mariadb_tzdata_mariadb_file.stat.exists | bool

        - name: Import the tzdata
          block:

            - name: Timezone database dump created
              ansible.builtin.shell: >
                set -e -o pipefail
                mysql_tzinfo_to_sql /usr/share/zoneinfo > /root/timezoneinfo.sql
              changed_when: true
              args:
                executable: "{{ ansible_local.bash.path | default('/usr/bin/bash') }}"

            - name: Check that the timezone database dump exists
              ansible.builtin.stat:
                path: /root/timezoneinfo.sql
              register: mariadb_tzdata_sql

            - name: Import the tzdata
              block:

                - name: Import the tzdata into the mysql database tables using the community.mysql.mysql_db module
                  community.mysql.mysql_db:
                    name: mysql
                    state: import
                    target: /root/timezoneinfo.sql
                    login_user: root
                    login_unix_socket: "{{ mariadb_socket }}"

                - name: /root/.my.tzdata file absent
                  ansible.builtin.file:
                    path: /root/.my.tzdata
                    state: absent
                  when: mariadb_tzdata_mariadb_file.stat.exists | bool

                - name: "/root/.my.tzdata file containing {{ mariadb_tzdata_latest }} present"
                  ansible.builtin.lineinfile:
                    path: /root/.my.tzdata
                    line: "{{ mariadb_tzdata_latest }}"
                    state: present
                    create: true
                    mode: 0640
                    owner: root
                    group: root

              when: mariadb_tzdata_sql.stat.exists | bool

          when: >-
            ( not mariadb_tzdata_mariadb_file.stat.exists | bool ) or
            ( ( mariadb_tzdata_mariadb_file.stat.exists | bool ) and
            ( mariadb_tzdata_mariadb != mariadb_tzdata_latest ) )

      when:
        - mariadb_tzdata_changelog.stat.exists is defined
        - mariadb_tzdata_changelog.stat.exists | bool

  tags:
    - mariadb
...
