---
- name: Check that the Debian tzdata changelog is present
  ansible.builtin.stat:
    path: /usr/share/doc/tzdata/changelog.Debian.gz
  register: mariadb_tzdata_changelog
  tags:
    - mariadb

- name: Update the timezone data
  block:

    - name: Get the latest date from the tzdata package changelog
      ansible.builtin.command: dpkg-parsechangelog -l /usr/share/doc/tzdata/changelog.Debian.gz -S Date
      check_mode: false
      changed_when: false
      register: mariadb_tzdata_deb_date

    - name: Set a fact for the date of the latest version
      ansible.builtin.set_fact:
        mariadb_tzdata_latest: "{{ mariadb_tzdata_deb_date.stdout }}"

    - name: Check if the /root/.my.tzdata file exists
      ansible.builtin.stat:
        path: /root/.my.tzdata
      register: mariadb_tzdata_mariadb_file

    - name: Tasks for when the /root/.my.tzdata file exists
      block:

        - name: Slurp the contents from the /root/.my.tzdata file
          ansible.builtin.slurp:
            src: /root/.my.tzdata
          register: mariadb_tzdata_mariadb_file_b64encoded

        - name: Set a fact for the date in the /root/.my.tzdata file
          ansible.builtin.set_fact:
            mariadb_tzdata_mariadb: "{{ mariadb_tzdata_mariadb_file_b64encoded['content'] | b64decode | trim }}"

        - name: Debug the value of mariadb_tzdata_mariadb and mariadb_tzdata_deb_date
          ansible.builtin.debug:
            msg:
              - "mariadb_tzdata_latest: {{ mariadb_tzdata_latest }}"
              - "mariadb_tzdata_mariadb: {{ mariadb_tzdata_mariadb }}"
            verbosity: 1

      when: mariadb_tzdata_mariadb_file.stat.exists

    - name: Import the tzdata into the mysql database tables using the shell module
      block:

        # Bash might be /bin/bash or /usr/bin/bash
        - name: Run which bash
          ansible.builtin.command: which bash
          check_mode: false
          changed_when: false
          register: which_bash
          failed_when: which_bash.stdout is not regex('\/bash$')

        - name: Set a variable for the path to Bash
          ansible.builtin.set_fact:
            bash: "{{ which_bash.stdout }}"

        - name: Import the time zone data from /usr/share/zoneinfo using the shell module
          ansible.builtin.shell: >
            set -e -o pipefail
            mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql
          args:
            executable: "{{ bash }}"
          notify: Restart mariadb

        - name: Update the /root/.my.tzdata file
          ansible.builtin.shell: >
            set -e -o pipefail
            dpkg-parsechangelog -l /usr/share/doc/tzdata/changelog.Debian.gz -S Date > /root/.my.tzdata
          args:
            executable: "{{ bash }}"

      when:
        - mariadb_root_auth_current == "password"
        - ( not mariadb_tzdata_mariadb_file.stat.exists ) or ( mariadb_tzdata_mariadb_file.stat.exists and mariadb_tzdata_mariadb != mariadb_tzdata_latest )

    - name: Import the tzdata into the mysql database tables using the community.mysql.mysql_db module
      community.mysql.mysql_db:
        name: all
        target: /usr/local/src/mariadb-sys/mariadb_sys_install.sql
        login_user: root
        login_unix_socket: "{{ mariadb_socket }}"
      when:
        - mariadb_root_auth_current == "socket"
        - ( not mariadb_tzdata_mariadb_file.stat.exists ) or ( mariadb_tzdata_mariadb_file.stat.exists and mariadb_tzdata_mariadb != mariadb_tzdata_latest )

    - name: /root/.my.tzdata file absent
      ansible.builtin.file:
        path: /root/.my.tzdata
        state: absent
      when: mariadb_tzdata_mariadb_file.stat.exists

    - name: "/root/.my.tzdata file containing {{ mariadb_tzdata_latest }} present"
      ansible.builtin.lineinfile:
        path: /root/.my.tzdata
        line: "{{ mariadb_tzdata_latest }}"
        state: present
        create: true
        mode: 640
        owner: root
        group: root

  when: ( mariadb_tzdata_changelog.stat.exists is defined ) and ( mariadb_tzdata_changelog.stat.exists )
  tags:
    - mariadb
...
