# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects MariaDB Ansible role.
#
# The Webarchitects MariaDB Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects MariaDB Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects MariaDB Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Debug MariaDB variables
  block:

    - name: Debug the mariadb_username variable
      ansible.builtin.debug:
        var: mariadb_username
      when: mariadb_username is defined

    - name: Debug the mariadb_database variable
      ansible.builtin.debug:
        var: mariadb_database
      when: mariadb_database is defined

    - name: Debug the mariadb_mycnf variable
      ansible.builtin.debug:
        var: mariadb_mycnf
      when: mariadb_mycnf is defined

    - name: Debug the mariadb_mycnf_owner variable
      ansible.builtin.debug:
        var: mariadb_mycnf_owner
      when: mariadb_mycnf_owner is defined

    - name: Debug the mariadb_mycnf_group variable
      ansible.builtin.debug:
        var: mariadb_mycnf_group
      when: mariadb_mycnf_group is defined

  tags:
    - mariadb
...
