---
- name: MariaDB database user, database and login details present
  block:

    - name: Include user variable checks
      ansible.builtin.include_tasks: user_checks.yml

    - name: "MariaDB database present {{ mariadb_database }}"
      community.mysql.mysql_db:
        login_user: root
        login_unix_socket: "{{ mariadb_socket }}"
        name: "{{ mariadb_database }}"
        state: present

    - name: "MariaDB user present {{ mariadb_username }}"
      community.mysql.mysql_user:
        login_user: root
        login_unix_socket: "{{ mariadb_socket }}"
        name: "{{ mariadb_username }}"
        password: "{{ mariadb_password }}"
        priv: "{{ mariadb_database }}.*:{% for mariadb_p in mariadb_priv %}{{ mariadb_p }}{% if not loop.last %},{% endif %}{% endfor %}"
        host: "{{ mariadb_host | default('localhost') }}"
        state: present
        update_password: always
      no_log: "{% if ansible_verbosity <= 2 %}true{% else %}false{% endif %}"

    - name: "MariaDB .my.cnf present at {{ mariadb_mycnf }}"
      include_tasks: conf.yml
      no_log: "{% if ansible_verbosity <= 2 %}true{% else %}false{% endif %}"
      vars:
        mariadb_config:
          - name: MariaDB user ~/.my.cnf configuration
            path: "{{ mariadb_mycnf }}"
            owner: "{{ mariadb_mycnf_owner }}"
            group: "{{ mariadb_mycnf_group }}"
            mode: "0400"
            state: present
            conf:
              client:
                user: "{{ mariadb_username }}"
                password: "{{ mariadb_password }}"

  tags:
    - mariadb
...
